name: Build flashcard-bootstrap Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    name: Build with Docker using BlocksDS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build dsbize patcher
        run: |
          sudo apt update
          sudo apt install -y python3 gcc
          gcc -o resource/dsbize/dsbize resource/dsbize/dsbize.c
          chmod +x resource/dsbize/dsbize
      - name: Make flashcard-bootstrap
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp bootstrap.zip ~/artifacts
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v3
        with:
          path: ~/artifacts/*
          name: build
      - name: Make release archive
        run: |
          cp devnotes.txt bootstrap/devnotes.txt
          cd bootstrap
          zip -r bootstrap.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bootstrap.zip
